# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orion_gui_dialog_asama3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(551, 261)
        Dialog.setMinimumSize(QtCore.QSize(551, 261))
        Dialog.setMaximumSize(QtCore.QSize(551, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.label_asama = QtWidgets.QLabel(Dialog)
        self.label_asama.setGeometry(QtCore.QRect(20, 20, 511, 61))
        self.label_asama.setMinimumSize(QtCore.QSize(511, 61))
        self.label_asama.setMaximumSize(QtCore.QSize(511, 61))
        self.label_asama.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_asama.setAlignment(QtCore.Qt.AlignCenter)
        self.label_asama.setWordWrap(True)
        self.label_asama.setObjectName("label_asama")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 90, 511, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.btn_color_red = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_color_red.setCheckable(False)
        self.btn_color_red.setObjectName("btn_color_red")
        self.horizontalLayout_6.addWidget(self.btn_color_red)
        self.btn_color_blue = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_color_blue.setCheckable(False)
        self.btn_color_blue.setObjectName("btn_color_blue")
        self.horizontalLayout_6.addWidget(self.btn_color_blue)
        self.btn_color_green = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_color_green.setCheckable(False)
        self.btn_color_green.setObjectName("btn_color_green")
        self.horizontalLayout_6.addWidget(self.btn_color_green)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_start = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        self.btn_cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AŞAMA -3-"))
        self.label_asama.setText(_translate("Dialog", "Aşama 3 esnasında patlatılacak balonların rengini seçin."))
        self.btn_color_red.setText(_translate("Dialog", "Kırmızı"))
        self.btn_color_blue.setText(_translate("Dialog", "Movi"))
        self.btn_color_green.setText(_translate("Dialog", "Yeşil"))
        self.btn_start.setText(_translate("Dialog", "Baslat"))
        self.btn_cancel.setText(_translate("Dialog", "Iptal"))
